### ISSUE TITLE
macOS build support

### ISSUE THREAD

**Issue by bsergean** [olesku/eventhub#7]
```
(venv) build$ cmake ..
-- Configuring done
-- Generating done
-- Build files have been written to: /Users/bsergeant/src/foss/github/eventhub/build
(venv) build$ make
Scanning dependencies of target libeventhub
[  3%] Building C object src/CMakeFiles/libeventhub.dir/http/picohttpparser.c.o
[  6%] Building CXX object src/CMakeFiles/libeventhub.dir/http/Parser.cpp.o
[ 10%] Building CXX object src/CMakeFiles/libeventhub.dir/http/Handler.cpp.o
In file included from /Users/bsergeant/src/foss/github/eventhub/src/http/Handler.cpp:7:
In file included from /Users/bsergeant/src/foss/github/eventhub/include/ConnectionWorker.hpp:11:
/Users/bsergeant/src/foss/github/eventhub/include/Connection.hpp:6:10: fatal error: 'sys/epoll.h' file not found
#include <sys/epoll.h>
         ^~~~~~~~~~~~~
1 error generated.
make[2]: *** [src/CMakeFiles/libeventhub.dir/http/Handler.cpp.o] Error 1
make[1]: *** [src/CMakeFiles/libeventhub.dir/all] Error 2
make: *** [all] Error 2
```

I was able to brew install hiredis and glog, compile and clone manually redis++, but it looks like epoll is the only option at this point. Maybe abstracting a bit of the Connection code could help to support select (or kqueue) wouldn't be too hard.

Is it something you'd like to support ? I could look at this on my (limited ...) spare time if this is interesting to you.

**Comment by bsergean** [comment]
https://github.com/antirez/redis/blob/unstable/src/ae_select.c
https://github.com/antirez/redis/blob/unstable/src/ae_epoll.c
https://github.com/antirez/redis/blob/unstable/src/ae.h

redis has this abstraction, maybe some code could be ripped of from there.

my lib code uses poll / PollResultType Socket::poll
https://github.com/machinezone/IXWebSocket/blob/master/ixwebsocket/IXSocket.cpp

First step would be to introduce one abstraction, use it on linux, make sure everything still work, and then implement the 'concrete' class for macOS.

**Comment by olesku** [comment]
Hi,

Yeah, sadly Linux is the only supported platform right now.
But I believe epoll/eventloop is the only dependency that is incompatible at this point.

Adding support for OSX and BSD is definitely on my todo-list, and I've actually done some research on kqueue, etc. as I was thinking to write an abstraction for the eventloop, exactly like you propose.

I ended up with a semi-plan to use [libuv](https://github.com/libuv/libuv) for this since it gives a lot for free out of the box. This library also has timers, thread pools, etc. which i currently use custom self made implementations for. The "negative" thing is that it is a C library and that you will need to write wrappers for using it safely in C++.

If you want to take a look at this I would be very, very thankful. It is not a requirement for me to use libuv. I just wanted to mention that since I've did some research on it earlier. I would be just as fine with an abstraction with epoll and kqueue implementation for now.

**Comment by bsergean** [comment]
Cool, yes libuv sounds like a good option. There's something called uvw which is a wrapper on top of libuv which seems good too.

In reality almost everyone would deploy on Linux, so only the epoll code path matter, but for development a bunch of people use macs. It looks like epoll is used in only a few file, so the simple abstraction approach should be sufficient. I'll try to code something up, but again no promises :)

**Comment by olesku** [comment]
Sounds great! 

Yeah, for most production deployments it is probably going to run on Linux. I myself have it in production right now running on Linux/Kubernetes, serving 100k+ clients.

But like you say developers tend to prefer macs, so it makes total sense to support it just for the sake of that. Also as a added bonus BSD should be supported as well once kqueue support is added.

I agree that the simple abstraction approach is sufficient, at least for the time being.
Looking really forward to a PR if you end up having the time to do so :).

**Comment by bsergean** [comment]
I'm working on a small epoll wrapper so that the code can stay exactly the same, and I just need to implement the 3 epoll functions using something else (I'm using select now which is very portable). I'll see where it goes...

**Comment by bsergean** [comment]
Beside the epoll thing, here's the only change I had to make to get the code to compile on osx.

There's another bind (std::function thing ?) so to get the system/unix/networky one I added the :: to tell it's the one from the global namespace.

diff --git a/src/Server.cpp b/src/Server.cpp
index 4c57d8e..7972636 100644
--- a/src/Server.cpp
+++ b/src/Server.cpp
@@ -48,7 +48,7 @@ void Server::start() {
   sin.sin_family = AF_INET;
   sin.sin_port   = htons(Config.getInt("LISTEN_PORT"));
 
-  LOG_IF(FATAL, (bind(_server_socket, (struct sockaddr*)&sin, sizeof(sin))) == -1) << "Could not bind server socket to port 8080";
+  LOG_IF(FATAL, (::bind(_server_socket, (struct sockaddr*)&sin, sizeof(sin))) == -1) << "Could not bind server socket to port 8080";

**Comment by bsergean** [comment]
I got something to run ... ! / but I'm definitely not sure about the code :) / it is only working if I have one worker thread.

Server

```
(venv) build$ env DISABLE_AUTH=1 WORKER_THREADS=1 ./eventhub
I1121 15:25:19.467864 338384320 Server.cpp:56] Listening on port 8080.
I1121 15:25:19.468598 338384320 Server.cpp:59] WARNING: Server is running with DISABLE_AUTH=true. Everything is allowed by any client.
I1121 15:25:19.468705 229081088 ConnectionWorker.cpp:197] Worker 1 started.
prep EPOLLIN on fd 3
set EPOLLIN on fd 3
prep EPOLLIN on fd 3
prep EPOLLIN on fd 6
set EPOLLIN on fd 6
prep EPOLLIN on fd 3
prep EPOLLIN on fd 6
set EPOLLIN on fd 6
prep EPOLLIN on fd 3
prep EPOLLIN on fd 6
set EPOLLIN on fd 6
prep EPOLLIN on fd 3
prep EPOLLIN on fd 6
set EPOLLIN on fd 6
I1121 15:25:31.281764 229081088 Handler.cpp:89] Failed to parse RPC request from 127.0.0.1: Parse error
```

Client

```
(venv) cobra$ ws connect ws://localhost:8080
Type Ctrl-D to exit prompt...
Connecting to url: ws://localhost:8080
ws_connect: connected
Uri: /
Handshake Headers:
connection: upgrade
sec-websocket-accept: 1gQtW1IULlsdzHZ5H7w6/AGHDbs=
sec-websocket-extensions: 
upgrade: websocket
> asdcasdc
> Received 104 bytes
ws_connect: received message: {"error":{"code":-32600,"data":"Invalid request","message":"Invalid request"},"id":null,"jsonrpc":"2.0"
```

**Comment by bsergean** [comment]
The threading bug was because I used std::cerr which isn't thread safe. The second I removed it everything worked fine...

**Comment by olesku** [comment]
Awesome work!

I'm looking to forward to look into this properly later today. Currently at work with no Mac to test on, but I have one at home :).

Tried to compile it on Linux with thread sanitizer but got no warnings here.
Will take a closer look at the race issues as well.

**Comment by olesku** [comment]
Hi again,

So i finally got to take a look at it on my Mac and i think i figured it out.

Fix can be seen in this commit: https://github.com/olesku/eventhub/commit/248771dfdd5b7cfcf9400ce48c4267231a7fd242

Basically my code expect each filedescriptor to be exclusive to the thread it is added to. This is done by setting the EPOLLEXCLUSIVE flag in Linux.

The wrapper was using a single _events map for all filedescriptors accross threads, which means any thread can recieve a event on any file descriptor. This causes issues if for example one thread deletes the client object while another thread is trying to write to it.

So my fix was basically to implement a exclusive event set to each thread using the epfd as key.

Code seems to run fine with multiple threads and requests on my mac now, but I would appreciate if you could do some verification as well :).

**Comment by bsergean** [comment]
Ah great, glad that you figured it out. I implemented a kqueue approach too / it could probably be improved but here it is in case it helps.

```
int epoll_wait_kqueue(int epfd, struct epoll_event *events,
                      int maxevents, int timeout) {
  int kqfd = kqueue();

  int setsize;
  {
    std::lock_guard<std::mutex> lock(mutex);
    setsize = _events.size();
  }

  struct kevent kevents[setsize];

  {
    std::lock_guard<std::mutex> lock(mutex);
    int i = 0;
    for (auto it : _events) {
      auto fd = it.first;
      auto ev = it.second;

      struct kevent ke = kevents[i];

      if (ev->events & EPOLLIN) {
        EV_SET(&ke, fd, EVFILT_READ, EV_ADD, 0, 0, NULL);
        kevent(kqfd, &ke, 1, NULL, 0, NULL);
      }

      if (ev->events & EPOLLOUT) {
        EV_SET(&ke, fd, EVFILT_WRITE, EV_ADD, 0, 0, NULL);
        kevent(kqfd, &ke, 1, NULL, 0, NULL);
      }

      // if (ev->events & EPOLLIN) {
      //   fds[i].events |= POLLIN;
      // }
      // if (ev->events & EPOLLOUT) {
      //   fds[i].events |= POLLOUT;
      // }
      // if (ev->events & EPOLLERR) {
      //   fds[i].events |= POLLERR;
      // }
      // if (ev->events & EPOLLRDHUP || ev->events & EPOLLHUP) {
      //   fds[i].events |= POLLHUP;
      // }

      i++;
    }
  }

  int retval;
  if (timeout != -1) {
      struct timespec tv;
      tv.tv_sec = timeout / 1000;
      tv.tv_nsec = (timeout % 1000) * 1000 * 1000;
      retval = kevent(kqfd, NULL, 0, kevents, setsize,
                      &tv);
  } else {
      retval = kevent(kqfd, NULL, 0, kevents, setsize,
                      NULL);
  }

  // if (retval < 0) {
  //   perror("kqueue error ");
  // }

  if (retval > 0) {
    int i = 0;
    for (int j = 0; j <= retval; j++) {
      bool pollIn  = kevents[j].filter == EVFILT_READ;
      bool pollOut = kevents[j].filter == EVFILT_WRITE;

      bool pollHup = kevents[j].flags & EV_EOF;
      bool pollErr = kevents[j].flags & EV_EOF;

      if (pollIn || pollOut || pollHup) {

        int fd = kevents[j].ident;

        std::lock_guard<std::mutex> lock(mutex);
        auto it = _events.find(fd);
        if (it != _events.end()) {
          struct epoll_event *e = it->second;

          events[i].events = 0;

          if (pollIn) {
            events[i].events |= EPOLLIN;
          }
          if (pollOut) {
            events[i].events |= EPOLLOUT;
          }
          if (pollErr) {
            events[i].events |= EPOLLERR;
          }
          if (pollHup) {
            events[i].events |= EPOLLHUP;
          }

          events[i].data.fd = fd;
          events[i].data.ptr = e->data.ptr;

          i++;
        }
      }
    }
  }

  return retval;
}
```

**Comment by bsergean** [comment]
Your fix works great.

Maybe we could implement special code to deal with EPOLLEXCLUSIVE, but we can just assume that this is how epoll is used in your project, and that's how the wrapper works.
